image: docker:latest

before_script:
    - docker info
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" docker.darookee.net

build:5.6:
    stage: build
    script:
        - docker build -t darookee/docker-php:5.6 cli/5.6
        - docker push darookee/docker-php:5.6

build:7.0:
    stage: build
    script:
        - docker build -t darookee/docker-php:7.0 cli/7.0
        - docker push darookee/docker-php:7.0
